title: Milo
description: >- # this means to ignore newlines until "baseurl:"
  A hub for my video game comic scanlations and other hobbies.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

show_excerpts: true

collections:
  scanlations:
    output: true
    sort_by: property

links:
  - url: https://www.twitch.tv/miloscatter
    text: Twitch
    thumbnail: assets/thumbnails/twitch.png
    logo: twitch
  - url: https://www.youtube.com/@MiloScat/videos
    text: Streams Archive
    thumbnail: assets/thumbnails/streams.png
    logo: youtube
  - url: https://miloscat.tumblr.com
    text: Game Reviews
    thumbnail: assets/thumbnails/reviews.png
    logo: tumblr
